version: "3.3"
services:
    db:
        image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: "MySql2021!"
          MYSQL_DATABASE: "lighthouse"
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_user_pass
        ports:
            - "3036:3036"
        volumes:
            - data:/var/lib/mysql
    app:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
volumes:
    data:

